# Copyright (c) 2019-2020 Phase Advanced Sensor Systems, Inc.
from .device import Device, Reg32, Reg32R, Reg32W


class SCS(Device):
    '''
    Driver for Cortex V6-M (M0+) System Control Space.
    '''
    REGS = [Reg32 ('ACTLR',  0x008),
            Reg32R('CPUID',  0xD00, [('REVISION',    4),
                                     ('PARTNO',     12),
                                     ('ONES',        4),
                                     ('VARIANT',     4),
                                     ('IMPLEMENTER', 8),
                                     ]),
            Reg32 ('ICSR',   0xD04, [('VECTACTIVE',  9),
                                     ('',            2),
                                     ('RETTOBASE',   1),
                                     ('VECTPENDING', 9),
                                     ('',            1),
                                     ('ISRPENDING',  1),
                                     ('ISRPREEMPT',  1),
                                     ('',            1),
                                     ('PENDSTCLR',   1),
                                     ('PENDSTSET',   1),
                                     ('PENDSVCLR',   1),
                                     ('PENDSVSET',   1),
                                     ('',            2),
                                     ('NMIPENDSET',  1),
                                     ]),
            Reg32 ('VTOR',   0xD08, [('',        7),
                                     ('TBLOFF', 25),
                                     ]),
            Reg32 ('AIRCR',  0xD0C, [('VECTRESET',     1),
                                     ('VECTCLRACTIVE', 1),
                                     ('SYSRESETREQ',   1),
                                     ('',              5),
                                     ('PRIGROUP',      3),
                                     ('',              4),
                                     ('ENDIANNESS',    1),
                                     ('VECTKEYSTAT',  16),
                                     ]),
            Reg32 ('SCR',    0xD10, [('',              1),
                                     ('SLEEPONEXIT',   1),
                                     ('SLEEPDEEP',     1),
                                     ('',              1),
                                     ('SEVONPEND',     1),
                                     ]),
            Reg32 ('CCR',    0xD14, [('NONBASETHRDENA', 1),
                                     ('USERSETMPEND',   1),
                                     ('',               1),
                                     ('UNALIGN_TRP',    1),
                                     ('DIV_0_TRP',      1),
                                     ('',               3),
                                     ('BFHFNMIGN',      1),
                                     ('STKALIGN',       1),
                                     ('',               6),
                                     ('DC',             1),
                                     ('IC',             1),
                                     ('BP',             1),
                                     ]),
            Reg32 ('SHPR2',  0xD1C, [('PRI_8',  8),
                                     ('PRI_9',  8),
                                     ('PRI_10', 8),
                                     ('PRI_11', 8),
                                     ]),
            Reg32 ('SHPR3',  0xD20, [('PRI_12', 8),
                                     ('PRI_13', 8),
                                     ('PRI_14', 8),
                                     ('PRI_15', 8),
                                     ]),
            Reg32 ('SHCSR',  0xD24, [('MEMFAULTACT',    1),
                                     ('BUSFAULTACT',    1),
                                     ('',               1),
                                     ('USGFAULTACT',    1),
                                     ('',               3),
                                     ('SVCALLACT',      1),
                                     ('MONITORACT',     1),
                                     ('',               1),
                                     ('PENDSVACT',      1),
                                     ('SYSTICKACT',     1),
                                     ('USGFAULTPENDED', 1),
                                     ('MEMFAULTPENDED', 1),
                                     ('BUSFAULTPENDED', 1),
                                     ('SVCALLPENDED',   1),
                                     ('MEMFAULTENA',    1),
                                     ('BUSFAULTENA',    1),
                                     ('USGFAULTENA',    1),
                                     ]),
            Reg32 ('DFSR',   0xD30, [('HALTED',      1),
                                     ('BKPT',        1),
                                     ('DWTTRAP',     1),
                                     ('VCATCH',      1),
                                     ('EXTERNAL',    1),
                                     ]),
            Reg32 ('DHCSR',  0xDF0, [('C_DEBUGEN',     1),
                                     ('C_HALT',        1),
                                     ('C_STEP',        1),
                                     ('C_MASKINTS',    1),
                                     ('',              1),
                                     ('C_SNAPSTALL',   1),
                                     ('',             10),
                                     ('S_REGRDY',      1),
                                     ('S_HALT',        1),
                                     ('S_SLEEP',       1),
                                     ('S_LOCKUP',      1),
                                     ('',              4),
                                     ('S_RETIRE_ST',   1),
                                     ('S_RESET_ST',    1),
                                     ]),
            Reg32W('DCRSR',  0xDF4, [('REGSEL',    7),
                                     ('',          9),
                                     ('REGWnR',    1),
                                     ]),
            #Reg32 ('DCRDR',  0xDF8),
            Reg32 ('DEMCR',  0xDFC, [('VC_CORERESET', 1),
                                     ('',             3),
                                     ('VC_MMERR',     1),
                                     ('VC_NOCPERR',   1),
                                     ('VC_CHKERR',    1),
                                     ('VC_STATEERR',  1),
                                     ('VC_BUSERR',    1),
                                     ('VC_INTERR',    1),
                                     ('VC_HARDERR',   1),
                                     ('',             5),
                                     ('MON_EN',       1),
                                     ('MON_PEND',     1),
                                     ('MON_STEP',     1),
                                     ('MON_REQ',      1),
                                     ('',             4),
                                     ('TRCENA',       1),
                                     ]),
            ]

    def __init__(self, target, ap, name, addr):
        super(SCS, self).__init__(target, ap, addr, name, SCS.REGS)
