# Copyright (c) 2025 by Phase Advanced Sensor Systems, Inc.
from ..device import Device, AReg32, Reg8S


class SPI_13x(Device):
    '''
    Driver for the STM32 1.3.x SPI device.
    '''
    REGS = [AReg32('CR1',       0x00,  [('CPHA',        0),
                                        ('CPOL',        1),
                                        ('MSTR',        2),
                                        ('BR',          3,  5),
                                        ('SPE',         6),
                                        ('LSBFIRST',    7),
                                        ('SSI',         8),
                                        ('SSM',         9),
                                        ('RXONLY',      10),
                                        ('CRCL',        11),
                                        ('CRCNEXT',     12),
                                        ('CRCEN',       13),
                                        ('BIDIOE',      14),
                                        ('BIDIMODE',    15),
                                        ]),
            AReg32('CR2',       0x04,  [('RXDMAEN',     0),
                                        ('TXDMAEN',     1),
                                        ('SSOE',        2),
                                        ('NSSP',        3),
                                        ('FRF',         4),
                                        ('ERRIE',       5),
                                        ('RXNEIE',      6),
                                        ('TXEIE',       7),
                                        ('DS',          8,  11),
                                        ('FRXTH',       12),
                                        ('LDMA_RX',     13),
                                        ('LDMA_TX',     14),
                                        ]),
            AReg32('SR',        0x08,  [('RXNE',        0),
                                        ('TXE',         1),
                                        ('CHSIDE',      2),
                                        ('UDR',         3),
                                        ('CRCERR',      4),
                                        ('MODF',        5),
                                        ('OVR',         6),
                                        ('BSY',         7),
                                        ('FRE',         8),
                                        ('FRLVL',       9,  10),
                                        ('FTLVL',       11, 12),
                                        ]),
            Reg8S('DR8',        0x0C,  [('DR',          8),
                                        ]),
            AReg32('CRCPR',     0x10,  [('CRCPOLY',     0,  15),
                                        ]),
            AReg32('RXCRCR',    0x14,  [('RXCRC',       0,  15),
                                        ]),
            AReg32('TXCRC',     0x18,  [('TXCRC',       0,  15),
                                        ]),
            AReg32('I2SCFGR',   0x1C,  [('CHLEN',       0),
                                        ('DATLEN',      1,  2),
                                        ('CKPOL',       3),
                                        ('I2SSTD',      4,  5),
                                        ('PCMSYNC',     7),
                                        ('I2SCFG',      8,  9),
                                        ('I2SE',        10),
                                        ('I2SMOD',      11),
                                        ('ASTRTEN',     12),
                                        ]),
            AReg32('I2SPR',     0x20,  [('I2SDIV',      0,  7),
                                        ('ODD',         8),
                                        ('MCKOE',       9),
                                        ]),
            ]

    def __init__(self, target, ap, name, addr, **kwargs):
        super().__init__(target, ap, addr, name, SPI_13x.REGS, **kwargs)
