# Copyright (c) 2022 Phase Advanced Sensor Systems, Inc.
from ..device import Device, AReg32


class SYSCFG(Device):
    '''
    Driver for the STM32U5 System Configuration Controller (SYSCFG) device.
    '''
    REGS = [AReg32('SECCFGR',           0x00,  [('SYSCFGSEC',       0),
                                                ('CLASSBSEC',       1),
                                                ('FPUSEC',          3),
                                                ]),
            AReg32('CFGR1',             0x04,  [('BOOSTEN',         8),
                                                ('ANASWVDD',        9),
                                                ('PB6_FMP',         16),
                                                ('PB7_FMP',         17),
                                                ('PB8_FMP',         18),
                                                ('PB9_FMP',         19),
                                                ('ENDCAP',          24, 25),
                                                ('SRAMCACHED',      28),
                                                ]),
            AReg32('FPUIMR',            0x08,  [('FPU_IE',          0,  5),
                                                ]),
            AReg32('CNSLCKR',           0x0C,  [('LOCKNSVTOR',      0),
                                                ('LOCKNSMPU',       1),
                                                ]),
            AReg32('CSLCKR',            0x10,  [('LOCKSVTAIRCR',    0),
                                                ('LOCKSMPU',        1),
                                                ('LOCKSAU',         2),
                                                ]),
            AReg32('CFGR2',             0x14,  [('CLL',             0),
                                                ('SPL',             1),
                                                ('PVDL',            2),
                                                ('ECCL',            3),
                                                ]),
            AReg32('MESR',              0x18,  [('MCLR',            0),
                                                ('IPMEE',           16),
                                                ]),
            AReg32('CCCSR',             0x1C,  [('EN1',             0),
                                                ('CS1',             1),
                                                ('EN2',             2),
                                                ('CS2',             3),
                                                ('EN3',             4),
                                                ('CS3',             5),
                                                ('RDY1',            8),
                                                ('RDY2',            9),
                                                ('RDY3',            10),
                                                ]),
            AReg32('CCVR',              0x20,  [('NCV1',            0,  3),
                                                ('PCV1',            4,  7),
                                                ('NCV2',            8,  11),
                                                ('PCV2',            12, 15),
                                                ('NCV3',            16, 19),
                                                ('PCV3',            20, 23),
                                                ]),
            AReg32('CCCR',              0x24,  [('NCC1',            0,  3),
                                                ('PCC1',            4,  7),
                                                ('NCC2',            8,  11),
                                                ('PCC2',            12, 15),
                                                ('NCC3',            16, 19),
                                                ('PCC3',            20, 23),
                                                ]),
            AReg32('RSSCMDR',           0x2C,  [('RSSCMD',          0,  15),
                                                ]),
            AReg32('OTGHSPHYCR',        0x74,  [('EN',              0),
                                                ('PDCTRL',          1),
                                                ('CLKSEL',          2,  5),
                                                ]),
            AReg32('OTGHSPHYTUNER2',    0x7C,  [('COMPDISTUNE',     0,  2),
                                                ('SQRXTUNE',        4,  6),
                                                ('TXPREEMPAMPTUNE', 13, 14),
                                                ]),
            ]

    def __init__(self, target, ap, name, addr, **kwargs):
        super().__init__(target, ap, addr, name, SYSCFG.REGS, **kwargs)
