# Copyright (c) 2019 Phase Advanced Sensor Systems, Inc.
from ..device import Device, Reg32, Reg32W


class GPT32(Device):
    '''
    Driver for the General-purpose Timer device (GPT) - TIM2 and TIM5.
    '''
    REGS = [Reg32 ('CR1',    0x000,    [('CEN',         1),
                                        ('UDIS',        1),
                                        ('URS',         1),
                                        ('OPM',         1),
                                        ('DIR',         1),
                                        ('CMS',         2),
                                        ('ARPE',        1),
                                        ('CKD',         2),
                                        ('',            1),
                                        ('UIFREMAP',    1),
                                        ('DITHEN',      1),
                                        ]),
            Reg32 ('CR2',    0x004,    [('',            3),
                                        ('CCDS',        1),
                                        ('MMS[2:0]',    3),
                                        ('TI1S',        1),
                                        ('',            17),
                                        ('MMS[3]',      1),
                                        ]),
            Reg32 ('SMCR',   0x008,    [('SMS[2:0]',    3),
                                        ('OCCS',        1),
                                        ('TS[2:0]',     3),
                                        ('MSM',         1),
                                        ('ETF',         4),
                                        ('ETPS',        2),
                                        ('ECE',         14),
                                        ('ETP',         1),
                                        ('SMS[3]',      1),
                                        ('',            3),
                                        ('TS[4:3]',     2),
                                        ('',            2),
                                        ('SMSPE',       1),
                                        ('SMSPS',       1),
                                        ]),
            Reg32 ('DIER',   0x00C,    [('UIE',         1),
                                        ('CC1IE',       1),
                                        ('CC2IE',       1),
                                        ('CC3IE',       1),
                                        ('CC4IE',       1),
                                        ('',            1),
                                        ('TIE',         1),
                                        ('',            1),
                                        ('UDE',         1),
                                        ('CC1DE',       1),
                                        ('CC2DE',       1),
                                        ('CC3DE',       1),
                                        ('CC4DE',       1),
                                        ('',            1),
                                        ('TDE',         1),
                                        ('',            5),
                                        ('IDXIE',       1),
                                        ('DIRIE',       1),
                                        ('IERRIE',      1),
                                        ('TERRIE',      1),
                                        ]),
            Reg32 ('SR',     0x010,    [('UIF',         1),
                                        ('CC1IF',       1),
                                        ('CC2IF',       1),
                                        ('CC3IF',       1),
                                        ('CC4IF',       1),
                                        ('',            1),
                                        ('TIF',         1),
                                        ('',            2),
                                        ('CC1OF',       1),
                                        ('CC2OF',       1),
                                        ('CC3OF',       1),
                                        ('CC4OF',       1),
                                        ('',            7),
                                        ('IDXF',        1),
                                        ('DIRF',        1),
                                        ('IERRF',       1),
                                        ('TERRF',       1),
                                        ]),
            Reg32W('EGR',    0x014,    [('UG',          1),
                                        ('CC1G',        1),
                                        ('CC2G',        1),
                                        ('CC3G',        1),
                                        ('CC4G',        1),
                                        ('',            1),
                                        ('TG',          1),
                                        ]),
            Reg32 ('CCMR1',  0x018),
            Reg32 ('CCMR2',  0x01C),
            Reg32 ('CCER',   0x020,    [('CC1E',        1),
                                        ]),
            Reg32 ('CNT',    0x024),
            Reg32 ('PSC',    0x028),
            Reg32 ('ARR',    0x02C),
            Reg32 ('CCR1',   0x034),
            Reg32 ('CCR2',   0x038),
            Reg32 ('CCR3',   0x03C),
            Reg32 ('CCR4',   0x040),
            Reg32 ('ECR',    0x058),
            Reg32 ('TISEL',  0x05C),
            Reg32 ('AF1',    0x060),
            Reg32 ('AF2',    0x064),
            Reg32 ('DCR',    0x3DC),
            Reg32 ('DMAR',   0x3E0),
            ]

    def __init__(self, target, ap, name, addr):
        super(GPT32, self).__init__(target, ap, addr, name, GPT32.REGS)
