# Copyright (c) 2026 Phase Advanced Sensor Systems, Inc.
from ..device import Device, AReg32


class PWR_03(Device):
    '''
    Driver for the STM32H503 Power Control (PWR) device.
    '''
    REGS = [AReg32('PMCR',          0x000, [('LPMS',            0),
                                            ('SVOS',            2,  3),
                                            ('CSSF',            7),
                                            ('FLPS',            9),
                                            ('BOOSTE',          12),
                                            ('AVD_READY',       13),
                                            ('SRAM2SO',         25),
                                            ('SRAM1SO',         26),
                                            ]),
            AReg32('PMSR',          0x004, [('STOPF',           5),
                                            ('SBF',             6),
                                            ]),
            AReg32('VOSCR',         0x010, [('VOS',             4,  5),
                                            ]),
            AReg32('VOSSR',         0x014, [('VOSRDY',          3),
                                            ('ACTVOSRDY',       13),
                                            ('ACTVOS',          14, 15),
                                            ]),
            AReg32('BDCR',          0x020, [('BREN',            0),
                                            ('MONEN',           1),
                                            ('VBE',             8),
                                            ('VBRS',            9),
                                            ]),
            AReg32('DBPCR',         0x024, [('DBP',             0),
                                            ]),
            AReg32('BDSR',          0x028, [('BRRDY',           16),
                                            ('VBATL',           20),
                                            ('VBATH',           21),
                                            ('TEMPL',           22),
                                            ('TEMPH',           23),
                                            ]),
            AReg32('SCCR',          0x030, [('BYPASS',          0),
                                            ('LDOEN',           8),
                                            ]),
            AReg32('VMCR',          0x034, [('PVDE',            0),
                                            ('PLS',             1,  3),
                                            ('AVDEN',           8),
                                            ('ALS',             9,  10),
                                            ]),
            AReg32('VMSR',          0x03C, [('AVDO',            19),
                                            ('VDDIO2RDY',       20),
                                            ('PVDO',            22),
                                            ]),
            AReg32('WUSCR',         0x040, [('CWUF1',           0),
                                            ('CWUF2',           1),
                                            ('CWUF3',           2),
                                            ('CWUF4',           3),
                                            ('CWUF5',           4),
                                            ]),
            AReg32('WUSR',          0x044, [('WUF1',            0),
                                            ('WUF2',            1),
                                            ('WUF3',            2),
                                            ('WUF4',            3),
                                            ('WUF5',            4),
                                            ]),
            AReg32('WUCR',          0x048, [('WUPEN1',          0),
                                            ('WUPEN2',          1),
                                            ('WUPEN3',          2),
                                            ('WUPEN4',          3),
                                            ('WUPEN5',          4),
                                            ('WUPP1',           8),
                                            ('WUPP2',           9),
                                            ('WUPP3',           10),
                                            ('WUPP4',           11),
                                            ('WUPP5',           12),
                                            ('WUPPUPD1',        16, 17),
                                            ('WUPPUPD2',        18, 19),
                                            ('WUPPUPD3',        20, 21),
                                            ('WUPPUPD4',        22, 23),
                                            ('WUPPUPD5',        24, 25),
                                            ]),
            AReg32('IORETR',        0x050, [('IORETEN',         0),
                                            ('JTAGIORETEN',     16),
                                            ]),
            AReg32('PRIVCFGR',      0x104, [('NSPRIV',          1),
                                            ]),
            ]

    def __init__(self, target, ap, name, addr, **kwargs):
        super().__init__(target, ap, addr, name, PWR_03.REGS, **kwargs)
