# Copyright (c) 2026 Phase Advanced Sensor Systems, Inc.
from ..device import Device, AReg32


ENABLE_BITS = {
    # AHB1
    'GPDMA1'        : (0x88,  0),
    'GPDMA2'        : (0x88,  1),
    'FLITF'         : (0x88,  8),
    'CRC'           : (0x88, 12),
    'RAMCFG'        : (0x88, 17),
    'GTZC1'         : (0x88, 24),
    'BKPRAM'        : (0x88, 28),
    'SRAM1'         : (0x88, 31),

    # AHB2
    'GPIOA'         : (0x8C,  0),
    'GPIOB'         : (0x8C,  1),
    'GPIOC'         : (0x8C,  2),
    'GPIOD'         : (0x8C,  3),
    'GPIOH'         : (0x8C,  7),
    'ADC'           : (0x8C, 10),
    'DAC12'         : (0x8C, 11),
    'HASH'          : (0x8C, 17),
    'RNG'           : (0x8C, 18),
    'SRAM2'         : (0x8C, 30),

    # APB1L
    'TIM2'          : (0x9C,  0),
    'TIM3'          : (0x9C,  1),
    'TIM6'          : (0x9C,  4),
    'TIM7'          : (0x9C,  5),
    'WWDG'          : (0x9C, 11),
    'OPAMP'         : (0x9C, 13),
    'SPI2'          : (0x9C, 14),
    'SPI3'          : (0x9C, 15),
    'COMP'          : (0x9C, 16),
    'USART2'        : (0x9C, 17),
    'USART3'        : (0x9C, 18),
    'I2C1'          : (0x9C, 21),
    'I2C2'          : (0x9C, 22),
    'I3C1'          : (0x9C, 23),
    'CRS'           : (0x9C, 24),

    # APB1H
    'DTS'           : (0xA0,  3),
    'LPTIM2'        : (0xA0,  5),
    'FDCAN'         : (0xA0,  9),

    # APB2
    'TIM1'          : (0xA4, 11),
    'SPI1'          : (0xA4, 12),
    'USART1'        : (0xA4, 14),
    'USB'           : (0xA4, 24),

    # APB3
    'SBS'           : (0xA8,  1),
    'LPUART1'       : (0xA8,  6),
    'I3C2'          : (0xA8,  9),
    'LPTIM1'        : (0xA8, 11),
    'RTCAPB'        : (0xA8, 21),
    }


class RCC_03(Device):
    '''
    Driver for STMH503 RCC device.
    '''
    REGS = [AReg32('CR',            0x000, [('HSION',           0),
                                            ('HSIRDY',          1),
                                            ('HSIKERON',        2),
                                            ('HSIDIV',          3,  4),
                                            ('HSIDIVF',         5),
                                            ('CSION',           8),
                                            ('CSIRDY',          9),
                                            ('CSIKERON',        10),
                                            ('HSI48ON',         12),
                                            ('HSI48RDY',        13),
                                            ('HSEON',           16),
                                            ('HSERDY',          17),
                                            ('HSEBYP',          18),
                                            ('HSECSSON',        19),
                                            ('HSEEXT',          20),
                                            ('PLL1ON',          24),
                                            ('PLL1RDY',         25),
                                            ('PLL2ON',          26),
                                            ('PLL2RDY',         27),
                                            ]),
            AReg32('HSICFGR',       0x010, [('HSICAL',          0,  11),
                                            ('HSITRIM',         16, 22),
                                            ]),
            AReg32('CRRCR',         0x014, [('HSI48CAL',        0,  9),
                                            ]),
            AReg32('CSICFGR',       0x018, [('CSICAL',          0,  7),
                                            ('CSITRIM',         16, 21),
                                            ]),
            AReg32('CFGR1',         0x01C, [('SW',              0,  1),
                                            ('SWS',             3,  4),
                                            ('STOPWUCK',        6),
                                            ('STOPKERWUCK',     7),
                                            ('RTCPRE',          8,  13),
                                            ('TIMPRE',          15),
                                            ('MCO1PRE',         18, 21),
                                            ('MCO1SEL',         22, 24),
                                            ('MCO2PRE',         25, 28),
                                            ('MCO2SEL',         29, 31),
                                            ]),
            AReg32('CFGR2',         0x020, [('HPRE',            0,  3),
                                            ('PPRE1',           4,  6),
                                            ('PPRE2',           8,  10),
                                            ('PPRE3',           12, 14),
                                            ('AHB1DIS',         16),
                                            ('AHB2DIS',         17),
                                            ('APB1DIS',         20),
                                            ('APB2DIS',         21),
                                            ('APB3DIS',         22),
                                            ]),
            AReg32('PLL1CFGR',      0x028, [('PLL1SRC',         0,  1),
                                            ('PLL1RGE',         2,  3),
                                            ('PLL1FRACEN',      4),
                                            ('PLL1VCOSEL',      5),
                                            ('PLL1M',           8,  13),
                                            ('PLL1PEN',         16),
                                            ('PLL1QEN',         17),
                                            ('PLL1REN',         18),
                                            ]),
            AReg32('PLL2CFGR',      0x02C, [('PLL2SRC',         0,  1),
                                            ('PLL2RGE',         2,  3),
                                            ('PLL2FRACEN',      4),
                                            ('PLL2VCOSEL',      5),
                                            ('PLL2M',           8,  13),
                                            ('PLL2PEN',         16),
                                            ('PLL2QEN',         17),
                                            ('PLL2REN',         18),
                                            ]),
            AReg32('PLL1DIVR',      0x034, [('PLL1N',           0,  8),
                                            ('PLL1P',           9,  15),
                                            ('PLL1Q',           16, 22),
                                            ('PLL1R',           24, 30),
                                            ]),
            AReg32('PLL1FRACR',     0x038, [('PLL1FRACN',       3,  15),
                                            ]),
            AReg32('PLL2DIVR',      0x03C, [('PLL2N',           0,  8),
                                            ('PLL2P',           9,  15),
                                            ('PLL2Q',           18, 22),
                                            ('PLL2R',           24, 30),
                                            ]),
            AReg32('PLL2FRACR',     0x040, [('PLL2FRACN',       3,  15),
                                            ]),
            AReg32('CIER',          0x050, [('LSIRDYIE',        0),
                                            ('LSERDYIE',        1),
                                            ('CSIRDYIE',        2),
                                            ('HSIRDYIE',        3),
                                            ('HSERDYIE',        4),
                                            ('HSI48RDYIE',      5),
                                            ('PLL1RDYIE',       6),
                                            ('PLL2RDYIE',       7),
                                            ]),
            AReg32('CIFR',          0x054, [('LSIRDYF',         0),
                                            ('LSERDYF',         1),
                                            ('CSIRDYF',         2),
                                            ('HSIRDYF',         3),
                                            ('HSERDYF',         4),
                                            ('HSI48RDYF',       5),
                                            ('PLL1RDYF',        6),
                                            ('PLL2RDYF',        7),
                                            ('HSECSSF',         10),
                                            ]),
            AReg32('CICR',          0x058, [('LSIRDYC',         0),
                                            ('LSERDYC',         1),
                                            ('CSIRDYC',         2),
                                            ('HSIRDYC',         3),
                                            ('HSERDYC',         4),
                                            ('HSI48RDYC',       5),
                                            ('PLL1RDYC',        6),
                                            ('PLL2RDYC',        7),
                                            ('HSECSSC',         10),
                                            ]),
            AReg32('AHB1RSTR',      0x060, [('GPDMA1RST',       0),
                                            ('GPDMA2RST',       1),
                                            ('CRCRST',          12),
                                            ('RAMCFGRST',       17),
                                            ]),
            AReg32('AHB2RSTR',      0x064, [('GPIOARST',        0),
                                            ('GPIOBRST',        1),
                                            ('GPIOCRST',        2),
                                            ('GPIODRST',        3),
                                            ('GPIOHRST',        7),
                                            ('ADCRST',          10),
                                            ('DAC1RST',         11),
                                            ('HASHRST',         17),
                                            ('RNGRST',          18),
                                            ]),
            AReg32('APB1LRSTR',     0x074, [('TIM2RST',         0),
                                            ('TIM3RST',         1),
                                            ('TIM6RST',         4),
                                            ('TIM7RST',         5),
                                            ('OPAMPRST',        13),
                                            ('SPI2RST',         14),
                                            ('SPI3RST',         15),
                                            ('COMPRST',         16),
                                            ('USART2RST',       17),
                                            ('USART3RST',       18),
                                            ('I2C1RST',         21),
                                            ('I2C2RST',         22),
                                            ('I3C1RST',         23),
                                            ('CRSRST',          24),
                                            ]),
            AReg32('APB1HRSTR',     0x078, [('DTSRST',          3),
                                            ('LPTIM2RST',       5),
                                            ('FDCANRST',        9),
                                            ]),
            AReg32('APB2RSTR',      0x07C, [('TIM1RST',         11),
                                            ('SPI1RST',         12),
                                            ('USART1RST',       14),
                                            ('USBRST',          24),
                                            ]),
            AReg32('APB3RSTR',      0x080, [('LPUART1RST',      6),
                                            ('I3CRST',          9),
                                            ('LPTIM1RST',       11),
                                            ]),
            AReg32('AHB1ENR',       0x088, [('GPDMA1EN',        0),
                                            ('GPDMA2EN',        1),
                                            ('FLITFEN',         8),
                                            ('CRCEN',           12),
                                            ('RAMCFGEN',        17),
                                            ('GTZC1EN',         24),
                                            ('BKPRAMEN',        28),
                                            ('SRAM1EN',         31),
                                            ]),
            AReg32('AHB2ENR',       0x08C, [('GPIOAEN',         0),
                                            ('GPIOBEN',         1),
                                            ('GPIOCEN',         2),
                                            ('GPIODEN',         3),
                                            ('GPIOHEN',         7),
                                            ('ADCEN',           10),
                                            ('DAC12EN',         11),
                                            ('HASHEN',          17),
                                            ('RNGEN',           18),
                                            ('SRAM2EN',         30),
                                            ]),
            AReg32('APB1LENR',      0x09C, [('TIM2EN',          0),
                                            ('TIM3EN',          1),
                                            ('TIM6EN',          4),
                                            ('TIM7EN',          5),
                                            ('WWDGEN',          11),
                                            ('OPAMPEN',         13),
                                            ('SPI2EN',          14),
                                            ('SPI3EN',          15),
                                            ('COMPEN',          16),
                                            ('USART2EN',        17),
                                            ('USART3EN',        18),
                                            ('I2C1EN',          21),
                                            ('I2C2EN',          22),
                                            ('I3C1EN',          23),
                                            ('CRSEN',           24),
                                            ]),
            AReg32('APB1HENR',      0x0A0, [('DTSEN',           3),
                                            ('LPTIM2EN',        5),
                                            ('FDCANEN',         9),
                                            ]),
            AReg32('APB2ENR',       0x0A4, [('TIM1EN',          11),
                                            ('SPI1EN',          12),
                                            ('USART1EN',        14),
                                            ('USBEN',           24),
                                            ]),
            AReg32('APB3ENR',       0x0A8, [('SBSEN',           1),
                                            ('LPUART1EN',       6),
                                            ('I3CEN',           9),
                                            ('LPTIM1EN',        11),
                                            ('RTCAPBEN',        21),
                                            ]),
            AReg32('AHB1LPENR',     0x0B0, [('GPDMA1LPEN',      0),
                                            ('GPDMA2LPEN',      1),
                                            ('FLITFLPEN',       8),
                                            ('CRCLPEN',         12),
                                            ('RAMCFGLPEN',      17),
                                            ('GTZC1LPEN',       24),
                                            ('BKPRAMLPEN',      28),
                                            ('ICACHELPEN',      29),
                                            ('SRAM1LPEN',       31),
                                            ]),
            AReg32('AHB2LPENR',     0x0B4, [('GPIOALPEN',       0),
                                            ('GPIOBLPEN',       1),
                                            ('GPIOCLPEN',       2),
                                            ('GPIODLPEN',       3),
                                            ('GPIOHLPEN',       7),
                                            ('ADCLPEN',         10),
                                            ('DAC12LPEN',       11),
                                            ('HASHLPEN',        17),
                                            ('RNGLPEN',         18),
                                            ('SRAM2LPEN',       30),
                                            ]),
            AReg32('APB1LLPENR',    0x0C4, [('TIM2LPEN',        0),
                                            ('TIM3LPEN',        1),
                                            ('TIM6LPEN',        4),
                                            ('TIM7LPEN',        5),
                                            ('WWDGLPEN',        11),
                                            ('OPAMPLPEN',       13),
                                            ('SPI2LPEN',        14),
                                            ('SPI3LPEN',        15),
                                            ('COMPLPEN',        16),
                                            ('USART2LPEN',      17),
                                            ('USART3LPEN',      18),
                                            ('I2C1LPEN',        21),
                                            ('I2C2LPEN',        22),
                                            ('I3C1LPEN',        23),
                                            ('CRSLPEN',         24),
                                            ]),
            AReg32('APB1HLPENR',    0x0C8, [('DTSLPEN',         3),
                                            ('LPTIM2LPEN',      5),
                                            ('FDCANLPEN',       9),
                                            ]),
            AReg32('APB2LPENR',     0x0CC, [('TIM1LPEN',        11),
                                            ('SPI1LPEN',        12),
                                            ('USART1LPEN',      14),
                                            ('USBLPEN',         24),
                                            ]),
            AReg32('APB3LPENR',     0x0D0, [('SBSLPEN',         1),
                                            ('LPUART1LPEN',     6),
                                            ('I3CLPEN',         9),
                                            ('LPTIM1LPEN',      11),
                                            ('RTCAPBLPEN',      21),
                                            ]),
            AReg32('CCIPR1',        0x0D8, [('USART1SEL',       0,  2),
                                            ('USART2SEL',       3,  5),
                                            ('USART3SEL',       6,  8),
                                            ('TIMICSEL',        31),
                                            ]),
            AReg32('CCIPR2',        0x0DC, [('LPTIM1SEL',       8,  10),
                                            ('LPTIM2SEL',       12, 14),
                                            ]),
            AReg32('CCIPR3',        0x0E0, [('SPI1SEL',         0,  2),
                                            ('SPI2SEL',         3,  5),
                                            ('SPI3SEL',         6,  8),
                                            ('LPUART1SEL',      24, 26),
                                            ]),
            AReg32('CCIPR4',        0x0E4, [('SYSTICKSEL',      2,  3),
                                            ('USBSEL',          4,  5),
                                            ('I2C1SEL',         16, 17),
                                            ('I2C2SEL',         18, 19),
                                            ('I3C1SEL',         24, 25),
                                            ('I3C2SEL',         26, 27),
                                            ]),
            AReg32('CCIPR5',        0x0E8, [('ADCDACSEL',       0,  2),
                                            ('DAC1SEL',         3),
                                            ('RNGSEL',          4,  5),
                                            ('FDCANSEL',        8,  9),
                                            ('CKPERSEL',        30, 31),
                                            ]),
            AReg32('BDCR',          0x0F0, [('LSEON',           0),
                                            ('LSERDY',          1),
                                            ('LSEBYP',          2),
                                            ('LSEDRV',          3,  4),
                                            ('LSECSSON',        5),
                                            ('LSECSSD',         6),
                                            ('LSEEXT',          7),
                                            ('RTCSEL',          8,  9),
                                            ('RTCEN',           15),
                                            ('VSWRST',          16),
                                            ('LSCOEN',          24),
                                            ('LSCOSEL',         25),
                                            ('LSION',           26),
                                            ('LSIRDY',          27),
                                            ]),
            AReg32('RSR',           0x0F4, [('RMVF',            23),
                                            ('PINRSTF',         26),
                                            ('BORRSTF',         27),
                                            ('SFTRSTF',         28),
                                            ('IWDGRSTF',        29),
                                            ('WWDGRSTF',        30),
                                            ('LPWRRSTF',        31),
                                            ]),
            AReg32('PRIVCFGR',      0x114, [('PRIV',            1),
                                            ]),
            ]

    def __init__(self, target, ap, name, addr, **kwargs):
        super().__init__(target, ap, addr, name, RCC_03.REGS, **kwargs)

    def enable_device(self, name):
        offset, bit = ENABLE_BITS[name]
        if self._get_field(1, bit, offset) == 0:
            self._set_field(1, 1, bit, offset)
