# Copyright (c) 2019 Phase Advanced Sensor Systems, Inc.
from ..device import Device, AReg32, AReg32W


class TIM15(Device):
    '''
    Driver for the H7 TIM15 General-purpose Timer device (GPT).
    '''
    REGS = [AReg32 ('CR1',    0x000,   [('CEN',                 0),
                                        ('UDIS',                1),
                                        ('URS',                 2),
                                        ('OPM',                 3),
                                        ('ARPE',                7),
                                        ('CKD',                 8,  9),
                                        ('UIFREMAP',            11),
                                        ]),
            AReg32 ('CR2',    0x004,   [('CCPC',                0),
                                        ('CCUS',                2),
                                        ('CCDS',                3),
                                        ('MMS',                 4,  6),
                                        ('TI1S',                7),
                                        ('OIS1',                8),
                                        ('OIS1N',               9),
                                        ('OIS2',                10),
                                        ]),
            AReg32 ('SMCR',   0x008,   [('SMS2_0',              0,  2),
                                        ('TS2_0',               4,  6),
                                        ('MSM',                 7),
                                        ('SMS_3',               16),
                                        ('TS4_3',               20, 21),
                                        ]),
            AReg32 ('DIER',   0x00C,   [('UIE',                 0),
                                        ('CC1IE',               1),
                                        ('CC2IE',               2),
                                        ('COMIE',               5),
                                        ('TIE',                 6),
                                        ('BIE',                 7),
                                        ('UDE',                 8),
                                        ('CC1DE',               9),
                                        ('COMDE',               13),
                                        ('TDE',                 14),
                                        ]),
            AReg32 ('SR',     0x010,   [('UIF',                 0),
                                        ('CC1IF',               1),
                                        ('CC2IF',               2),
                                        ('COMIF',               5),
                                        ('TIF',                 6),
                                        ('BIF',                 7),
                                        ('CC1OF',               9),
                                        ('CC2OF',               10),
                                        ]),
            AReg32W('EGR',    0x014,   [('UG',                  0),
                                        ('CC1G',                1),
                                        ('CC2G',                2),
                                        ('COMG',                5),
                                        ('TG',                  6),
                                        ('BG',                  7),
                                        ]),
            AReg32 ('CCMR1_I',  0x018, [('CC1S',                0,  1),
                                        ('IC1PSC',              2,  3),
                                        ('IC1F',                4,  7),
                                        ('CC2S',                8,  9),
                                        ('IC2PSC',              10, 11),
                                        ('IC2F',                12, 15),
                                        ]),
            AReg32 ('CCMR1_O',  0x018, [('CC1S',                0,  1),
                                        ('OC1FE',               2),
                                        ('OC1PE',               3),
                                        ('OC1M2_0',             4,  6),
                                        ('CC2S',                8,  9),
                                        ('OC2FE',               10),
                                        ('OC2PE',               11),
                                        ('OC2M2_0',             12, 14),
                                        ('OC1M_3',              16),
                                        ('OC2M_3',              24),
                                        ]),
            AReg32 ('CCER',   0x020,   [('CC1E',                0),
                                        ('CC1P',                1),
                                        ('CC1NE',               2),
                                        ('CC1NP',               3),
                                        ('CC2E',                4),
                                        ('CC2P',                5),
                                        ('CC2NP',               7),
                                        ]),
            AReg32 ('CNT',    0x024,   [('CNT',                 0,  15),
                                        ('UIFCPY',              31),
                                        ]),
            AReg32 ('PSC',    0x028,   [('PSC',                 0,  15),
                                        ]),
            AReg32 ('ARR',    0x02C,   [('ARR',                 0,  15),
                                        ]),
            AReg32 ('RCR',    0x030,   [('REP',                 0,  7),
                                        ]),
            AReg32 ('CCR1',   0x034,   [('CCR1',                0,  15),
                                        ]),
            AReg32 ('CCR2',   0x038,   [('CCR2',                0,  15),
                                        ]),
            AReg32 ('BDTR',   0x044,   [('DTG',                 0,  7),
                                        ('LOCK',                8,  9),
                                        ('OSSI',                10),
                                        ('OSSR',                11),
                                        ('BKE',                 12),
                                        ('BKP',                 13),
                                        ('AOE',                 14),
                                        ('MOE',                 15),
                                        ('BKF',                 16, 19),
                                        ('BKDSRM',              26),
                                        ('BKBID',               28),
                                        ]),
            AReg32 ('DCR',    0x048,   [('DBA',                 0,  4),
                                        ('DBL',                 8,  12),
                                        ]),
            AReg32 ('DMAR',   0x04C,   [('DMAB',                0,  15),
                                        ]),
            AReg32 ('AF1',    0x060,   [('BKINE',               0),
                                        ('BKCMP1E',             1),
                                        ('BKCMP2E',             2),
                                        ('BKDF1BK0E',           8),
                                        ('BKINP',               9),
                                        ('BKCMP1P',             10),
                                        ('BKCMP2P',             11),
                                        ]),
            AReg32 ('TISEL',  0x068,   [('TI1SEL',              0,  3),
                                        ('TI2SEL',              8,  11),
                                        ]),
            ]

    def __init__(self, target, ap, name, addr, **kwargs):
        super().__init__(target, ap, addr, name, TIM15.REGS, **kwargs)
